### ISSUE TITLE
user2 password wrong in AD DC

### ISSUE THREAD

**Issue by MattDierick** [teamaccessonline/library#35]
**Which Solution is experiencing issues**
[https://teamaccesssolutions.readthedocs.io/en/latest/labs/class3/module2/lab007.html](https://teamaccesssolutions.readthedocs.io/en/latest/labs/class3/module2/lab007.html)

**Describe the bug**
user2 password is not set to user2

**To Reproduce**
- Without changing the password in AD DC, try to connect to user2/user2

**Additional context**
Reseting password in AD DC for user2 with passwd user2 fix the issue.

**Comment by jmack707** [comment]
The latest blueprint update resolves the user2 password problem. The current blueprint version is 39.

**Comment by yahshun** [comment]
Sorry guys that was my fault.  When I moved the AD APIs under version control Friday night I ran my collection to test make sure all the APIs still worked.  One of those API changed user2's password.  I modified by Postman Collection this morning so when I'm testing I use accounts the collection creates rather user1 or user2 accounts that labs and solutions use.  The issue should be fixed in the latest blueprint release.  Version 39.
